# Serve the CMS app for /admin and anything under it
[[redirects]]
  from = "/admin"
  to   = "/admin/index.html"
  status = 200

[[redirects]]
  from = "/admin/*"
  to   = "/admin/index.html"
  status = 200

# SPA catch-all for the rest of the site
[[redirects]]
  from = "/*"
  to   = "/index.html"
  status = 200
[[plugins]]
  package = "@netlify/plugin-functions-install-core"

[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200
  conditions = { Role = ["admin"] }
