backend:
  name: git-gateway
  branch: main

site_url: https://condo-database.com

# ให้ Media library เห็นโฟลเดอร์หลัก
media_folder: "images/upload"
public_folder: "/images/upload"

collections:
  - name: "owners"
    label: "Owners (private)"
    folder: "content/owners"
    create: true
    slug: "{{name}}"
    fields:
      - { label: "Owner name", name: "name", widget: "string" }
      - { label: "Phone number", name: "phone", widget: "string", required: false }
      - { label: "LINE ID", name: "line", widget: "string", required: false }
      - { label: "WhatsApp", name: "whatsapp", widget: "string", required: false }
      - { label: "Email", name: "email", widget: "string", required: false }
      - { label: "Notes (internal)", name: "notes", widget: "text", required: false }

  - name: "listings"
    label: "Listings"
    folder: "content/listings"
    create: true

    # ใช้ Property ID เป็นชื่อไฟล์ content (คงรูปแบบ/ตัวพิมพ์)
    slug: "{{fields.property_id}}"
    slugify:
      lower: false

    # ใช้ slug ของเอนทรี (เช่น cdb-00246) เพื่อให้ตรงกับชื่อโฟลเดอร์จริง
    media_folder: "images/upload/listings/{{slug}}"
    public_folder: "/images/upload/listings/{{slug}}"

    summary: "{{title}} — ID: {{property_id}} — {{location}} — Rent ฿{{rent_price}} / Sale ฿{{sale_price}} — {{availability}}"

    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Property ID", name: "property_id", widget: "string", required: true, hint: "Use your own code (e.g. CDB-00246). Must be unique." }

      - label: "Date"
        name: "date"
        widget: "datetime"
        date_format: "YYYY-MM-DD"
        time_format: false
        required: false
        hint: "Used for 'Newest' sorting on the listings page"

      - label: "Availability"
        name: "availability"
        widget: "select"
        options: ["Available", "Rented", "Sold", "Reserved"]
        default: "Available"

      - label: "Rented until"
        name: "rented_until"
        widget: "datetime"
        date_format: "YYYY-MM-DD"
        time_format: false
        required: false

      - label: "Status"
        name: "status"
        widget: "select"
        options: ["Rent", "Sale", "Rent & Sale"]
        default: "Rent"

      - label: "Rent price (THB/month)"
        name: "rent_price"
        widget: "number"
        value_type: "int"
        min: 0
        step: 1000
        required: false

      - label: "Sale price (THB)"
        name: "sale_price"
        widget: "number"
        value_type: "int"
        min: 0
        step: 10000
        required: false

      - label: "Price (deprecated)"
        name: "price"
        widget: "number"
        value_type: "int"
        min: 0
        step: 1000
        required: false
        hint: "Legacy field. Use Rent/Sale price above."

      - { label: "Project", name: "project", widget: "string" }
      - { label: "Location", name: "location", widget: "string", default: "Bangkok" }
      - { label: "Google Maps Link", name: "maps_url", widget: "string", required: false, hint: "Paste a full Google Maps URL (optional)" }
      - { label: "Pet friendly", name: "pet_friendly", widget: "boolean", default: false }
      - { label: "Bedrooms", name: "bedrooms", widget: "number", value_type: "int", min: 0 }
      - { label: "Bathrooms", name: "bathrooms", widget: "number", value_type: "int", min: 0 }
      - { label: "Size (sqm)", name: "size", widget: "number", value_type: "float", min: 0, step: 0.5 }
      - { label: "Floor", name: "floor", widget: "number", min: 1, required: false }

      - label: "Cover image"
        name: "cover_image"
        widget: "image"
        required: false
        hint: "Shown first on the card. You can also reorder the Gallery below."

      - label: "Gallery"
        name: "images"
        widget: "list"
        allow_add: true
        collapsed: false
        hint: "Upload multiple or choose existing. Drag to reorder."
        fields:
          - { label: "Image", name: "image", widget: "image" }
          - { label: "Caption (optional)", name: "caption", widget: "string", required: false }
          - { label: "Alt text (optional)", name: "alt", widget: "string", required: false }

      - { label: "Description", name: "body", widget: "markdown" }

      - label: "Owner (private)"
        name: "owner"
        widget: "relation"
        collection: "owners"
        search_fields: ["name", "phone", "email"]
        value_field: "{{slug}}"
        display_fields: ["name", "phone"]
        required
