backend:
  name: git-gateway
  branch: main

site_url: https://condo-database.com

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  # ---------------------------
  # Owners (private data)
  # ---------------------------
  - name: "owners"
    label: "Owners (private)"
    folder: "content/owners"
    create: true
    slug: "{{name}}"
    fields:
      - { label: "Owner name", name: "name", widget: "string" }
      - { label: "Phone number", name: "phone", widget: "string", required: false }
      - { label: "LINE ID", name: "line", widget: "string", required: false }
      - { label: "WhatsApp", name: "whatsapp", widget: "string", required: false }
      - { label: "Email", name: "email", widget: "string", required: false }
      - { label: "Notes (internal)", name: "notes", widget: "text", required: false }

  # ---------------------------
  # Listings
  # ---------------------------
  - name: "listings"
    label: "Listings"
    folder: "content/listings"
    create: true
    slug: "{{slug}}"
    summary: "{{title}} — ID: {{property_id}} — {{location}} — ฿{{rent_price}}{{sale_price}} — {{availability}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Property ID", name: "property_id", widget: "string", required: false }

      - { label: "Availability", name: "availability", widget: "select",
          options: ["Available", "Rented", "Sold", "Reserved"] }

      - label: "Rented until"
        name: "rented_until"
        widget: "datetime"
        date_format: "YYYY-MM-DD"
        time_format: false
        required: false

      # NEW: status supports both
      - { label: "Status", name: "status", widget: "select",
          options: ["Rent", "Sale", "Rent & Sale"] }

      # NEW: separate prices
      - { label: "Rent price (THB/month)", name: "rent_price", widget: "number",
          value_type: "int", min: 0, step: 1000, required: false }
      - { label: "Sale price (THB)", name: "sale_price", widget: "number",
          value_type: "int", min: 0, step: 10000, required: false }

      # Back-compat (optional; you can remove later)
      - { label: "Price (deprecated)", name: "price", widget: "number",
          value_type: "int", min: 0, step: 1000, required: false,
          hint: "Legacy field. Use Rent/Sale price above." }

      - { label: "Project", name: "project", widget: "string" }
      - { label: "Location", name: "location", widget: "string", default: "Bangkok" }
      - { label: "Google Maps Link", name: "maps_url", widget: "string", required: false, hint: "Paste the full Google Maps URL (optional)" }
      - { label: "Pet friendly", name: "pet_friendly", widget: "boolean", default: false }

      - { label: "Bedrooms", name: "bedrooms", widget: "number", value_type: "int", min: 0 }
      - { label: "Bathrooms", name: "bathrooms", widget: "number", value_type: "int", min: 0 }
      - { label: "Size (sqm)", name: "size", widget: "number", value_type: "float", min: 0, step: 0.5 }

      - label: "Gallery"
        name: "images"
        widget: "list"
        field: { label: "Image", name: "image", widget: "image" }

      - { label: "Description", name: "body", widget: "markdown" }

      - label: "Owner (private)"
        name: "owner"
        widget: "relation"
        collection: "owners"
        search_fields: ["name", "phone", "email"]
        value_field: "{{slug}}"
        display_fields: ["name", "phone"]
        required: false
